Add support for casting expressions
micronaut-projects/micronaut-sourcegen pull request #146
Opened 2024-09-22 09:25 UTC by andriy-dmytruk

Add support for casting expressions that will look like:
* `(Type) value` for Java/Groovy
* `value as Type` for Kotlin

Seems required for https://github.com/micronaut-projects/micronaut-sourcegen/issues/126.

2024-09-22 16:44 UTC, graemerocher approved these changes

2024-09-23 07:04 UTC, dstepanov requested changes

2024-09-23 07:04 UTC, dstepanov commented on test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyBean3Visitor.java
> +                    new ExpressionDef.Cast(
Please add a default method to `ExpressionDef` `cast`, so this statement can we written as:
```
        new VariableDef.MethodParameter(
            "value",
            TypeDef.primitive(Double.TYPE)
        ).cast(Float.TYPE).returning()
```

or

```
.build(self, parameters) -> parameters.get(0).cast(Float.TYPE).returning()
```

2024-09-23 09:41 UTC, dstepanov approved these changes

2024-09-23 09:41 UTC, merged