Adding inner types to objectDef
micronaut-projects/micronaut-sourcegen pull request #169
Opened 2024-10-28 17:22 UTC by elifKurtay

The implementation of [the issue #160](https://github.com/micronaut-projects/micronaut-sourcegen/issues/160#issue-2611898495)

- Records, enums, classes and interfaces can be created inside themselves using `.addInnerType(ObjectDef)`. 
- Inner types inside an interface automatically and explicitly gets the `public` and `static` modifiers.

2024-10-30 16:40 UTC, andriy-dmytruk commented on test-suite-kotlin/src/test/kotlin/io/micronaut/sourcegen/example/InnerTypesGenerationTest.kt
> +package io.micronaut.sourcegen.example
This should be in `sourcegen-generator-kotlin/test`

2024-10-30 16:40 UTC, andriy-dmytruk commented on test-suite-kotlin/build.gradle.kts
> +    implementation(projects.sourcegenModel)
This is not needed.

2024-11-01 14:37 UTC, andriy-dmytruk approved these changes

2024-11-01 15:16 UTC, dstepanov requested changes

2024-11-01 15:16 UTC, dstepanov commented on test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/innerTypes/GenerateInnerTypeInEnumVisitor.java
> +                .addStatement(new StatementDef.Return(
Please correct tests not to use `new` Statement / Expression, you should be able to write everything without it using flow style. See `build((aThis, parameters) -> ` use cases. In this case, it should be `aThis.invoke("string"...).returning()`

2024-11-01 17:29 UTC, dstepanov approved these changes

2024-11-01 17:29 UTC, dstepanov commented on test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/innerTypes/GenerateInnerTypeInEnumVisitor.java
> +                        aThis.invoke("toString", TypeDef.STRING, List.of()).returning()))
Why do you keep using `List.of`? There is an array variation, and you can omit the parameters.

2024-11-01 19:28 UTC, merged