Allow to add Javadoc
micronaut-projects/micronaut-sourcegen pull request #25
Opened 2024-01-16 13:53 UTC by dstepanov

Not sure how to test it

2024-01-16 13:54 UTC, graemerocher requested changes

2024-01-16 13:54 UTC, graemerocher commented on sourcegen-model/src/main/java/io/micronaut/sourcegen/model/AnnotationDef.java
> +            System.err.println("BBB " + requiredType + " " + value);
probably a mistake?

2024-01-16 14:20 UTC, dstepanov commented on sourcegen-model/src/main/java/io/micronaut/sourcegen/model/AnnotationDef.java
> +            System.err.println("BBB " + requiredType + " " + value);
Removed

2024-01-17 08:10 UTC, graemerocher approved these changes

2024-01-17 08:10 UTC, merged